//TODO zmienic ustwienia postgresa, poza portem 5432 odrzuca polaczenia gdy inny kontener jest w tej samej sieci
version: '3.7'
services:
  backend-spring:
    container_name: backend_spring
    restart: always
    build:
      context: mgr-backend-spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres-spring:
    container_name: postgres-spring
    image: library/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres_spring
      - POSTGRES_PASSWORD=postgres_spring
      - POSTGRES_DB=performance_spring

  backend-node:
    container_name: backend_node
    restart: always
    build:
      context: mgr-backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres-node:
    container_name: postgres-node
    image: library/postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres_node
      - POSTGRES_PASSWORD=postgres_node
      - POSTGRES_DB=performance_node